### ISSUE TITLE
I an unable to start the server help me  i am using ####npm run dev-server command and getting error 

### ISSUE THREAD

**Issue by ghost** [AlexandreRavichandran/Quiver#1]
![IMG_20240319_122417](https://github.com/AlexandreRavichandran/Quiver/assets/134361687/4e7c19e3-c821-45d3-b2d8-a737a1d0fc6e)
What command I have to use....

**Comment by AlexandreRavichandran** [comment]
Hello
This is a Symfony monolith project, so you have to open it with Symfony CLI
please follow the steps described in the README.md

**Comment by ghost** [comment]
Sir  please tell me each step  how to configure all project how will i
configure symfony and configure  project









H

**Comment by AlexandreRavichandran** [comment]
Please install Symfony CLI first https://symfony.com/doc/current/setup.html

Then follow my readme https://github.com/AlexandreRavichandran/Quiver/blob/master/README.md
